<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Model">
  <eAnnotations source="Author:jerkerdelsing.&#xA;Created:2012-10-01, 15:10.&#xA;Title:.&#xA;Comment:.&#xA;"
      references="#/"/>
  <eAnnotations source="JD - Group Tool"/>
  <eSubpackages name="Unit Imports">
    <eSubpackages name="Basic Units">
      <eSubpackages name="Basic Length"/>
      <eSubpackages name="Basic Mass"/>
      <eSubpackages name="Basic Area"/>
      <eSubpackages name="Basic Volume"/>
      <eSubpackages name="Basic Time"/>
      <eSubpackages name="Basic Electric Current"/>
      <eSubpackages name="Basic Thermodynamic Temperature"/>
      <eSubpackages name="Basic Amount of Substance"/>
      <eSubpackages name="Basic Luminous Intensity"/>
      <eSubpackages name="Basic Speed and Velocity"/>
      <eSubpackages name="Basic Acceleration"/>
      <eSubpackages name="Basic Mass Density"/>
      <eSubpackages name="Basic Electric Current Density"/>
      <eSubpackages name="Basic Amount of Substance Concentration"/>
      <eSubpackages name="Basic Magnetic Field Strength"/>
      <eSubpackages name="Basic Luminance"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Tank control">
    <eSubpackages name="Use case Tank Control"/>
    <eSubpackages name="Level">
      <eClassifiers xsi:type="ecore:EClass" name="TankLevel-DD" eSuperTypes="#//Tank%20control/Level/TankLevel"/>
      <eClassifiers xsi:type="ecore:EClass" name="LevelSensor-DesignDescription" eSuperTypes="#//Tank%20control/Level/LevelSensor-Design"/>
      <eClassifiers xsi:type="ecore:EClass" name="TankLevel-CoAP" eSuperTypes="#//Tank%20control/Level/TankLevel">
        <eOperations name="Level" ordered="false" lowerBound="1"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Security" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//SecurityKind"
            defaultValueLiteral="CERTIFICATE"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="CertificateLevel" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//CertificateKind"
            defaultValueLiteral="System"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Protocol" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//ProtocolKind"
            defaultValueLiteral="CoAP"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Encoding" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//EncodingKind"
            defaultValueLiteral="JSON"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TankLevel">
        <eOperations name="Level" ordered="false" lowerBound="1" eType="ecore:EDataType SysML_Profile.ecore#//Libraries/PrimitiveValueTypes/String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LevelSensor-Design"/>
      <eClassifiers xsi:type="ecore:EClass" name="LevelSensor-Implementation" eSuperTypes="#//Tank%20control/Level/LevelSensor-DesignDescription"/>
      <eClassifiers xsi:type="ecore:EClass" name="Security-policy" interface="true"/>
    </eSubpackages>
    <eSubpackages name="HMI">
      <eClassifiers xsi:type="ecore:EClass" name="HMI-Design"/>
      <eClassifiers xsi:type="ecore:EClass" name="HMI_DesignDescription" eSuperTypes="#//Tank%20control/HMI/HMI-Design"/>
      <eClassifiers xsi:type="ecore:EClass" name="Configuration">
        <eOperations name="ConfigControler">
          <eParameters name="Data_input" ordered="false" lowerBound="1"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Configuration-DD" eSuperTypes="#//Tank%20control/HMI/Configuration"/>
      <eClassifiers xsi:type="ecore:EClass" name="Configuration-CoAP" eSuperTypes="#//Tank%20control/HMI/Configuration">
        <eOperations name="ConfigControler" ordered="false" lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//StatusCodeKind">
          <eParameters name="Data_input" ordered="false" lowerBound="1"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Security" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//SecurityKind"
            defaultValueLiteral="CERTIFICATE"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="CertificateLevel" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//CertificateKind"
            defaultValueLiteral="System"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Protocol" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//ProtocolKind"
            defaultValueLiteral="CoAP"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Encoding" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//EncodingKind"
            defaultValueLiteral="JSON"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HMI-Implementation" eSuperTypes="#//Tank%20control/HMI/HMI_DesignDescription"/>
    </eSubpackages>
    <eSubpackages name="Flow">
      <eClassifiers xsi:type="ecore:EClass" name="FlowSensor-Design"/>
      <eClassifiers xsi:type="ecore:EClass" name="FlowSensor-DesignDescription" eSuperTypes="#//Tank%20control/Flow/FlowSensor-Design"/>
      <eClassifiers xsi:type="ecore:EClass" name="Flow">
        <eOperations name="Flow" ordered="false" lowerBound="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Flow-CoAP" eSuperTypes="#//Tank%20control/Flow/Flow">
        <eOperations name="Flow" ordered="false" lowerBound="1" eType="ecore:EDataType SysML_Profile.ecore#//Libraries/PrimitiveValueTypes/String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Security" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//SecurityKind"
            defaultValueLiteral="CERTIFICATE"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="CertificateLevel" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//CertificateKind"
            defaultValueLiteral="System"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Protocol" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//ProtocolKind"
            defaultValueLiteral="CoAP"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Encoding" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//EncodingKind"
            defaultValueLiteral="JSON"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Flow-DD" eSuperTypes="#//Tank%20control/Flow/Flow"/>
      <eClassifiers xsi:type="ecore:EClass" name="FlowSensor-Implementation" eSuperTypes="#//Tank%20control/Flow/FlowSensor-DesignDescription">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint1" ordered="false"
            lowerBound="1"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Controler">
      <eClassifiers xsi:type="ecore:EClass" name="Controler-Design"/>
      <eClassifiers xsi:type="ecore:EClass" name="Controler-DesignDescription" eSuperTypes="#//Tank%20control/Controler/Controler-Design"/>
      <eClassifiers xsi:type="ecore:EClass" name="Controler-Implementation" eSuperTypes="#//Tank%20control/Controler/Controler-DesignDescription"/>
    </eSubpackages>
    <eSubpackages name="Valve">
      <eClassifiers xsi:type="ecore:EClass" name="Valve-Design">
        <eStructuralFeatures xsi:type="ecore:EAttribute" ordered="false" lowerBound="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Valve_DesignDescription" eSuperTypes="#//Tank%20control/Valve/Valve-Design"/>
      <eClassifiers xsi:type="ecore:EClass" name="Valve-Implementation" eSuperTypes="#//Tank%20control/Valve/Valve_DesignDescription"/>
      <eClassifiers xsi:type="ecore:EClass" name="SetPoint">
        <eOperations name="SetPoint">
          <eParameters name="SetPoint" ordered="false" lowerBound="1"/>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SetPoint-CoAP" eSuperTypes="#//Tank%20control/Valve/SetPoint">
        <eOperations name="SetPoint" ordered="false" lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//StatusCodeKind">
          <eParameters name="SetPoint" ordered="false" lowerBound="1"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Security" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//SecurityKind"
            defaultValueLiteral="CERTIFICATE"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="CertificateLevel" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//CertificateKind"
            defaultValueLiteral="System"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Protocol" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//ProtocolKind"
            defaultValueLiteral="CoAP"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Encoding" ordered="false"
            lowerBound="1" eType="ecore:EEnum Arrowhead_Profile-JD-84b_experimental.ecore#//EncodingKind"
            defaultValueLiteral="JSON"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SetPoint-DD" eSuperTypes="#//Tank%20control/Valve/SetPoint"/>
    </eSubpackages>
    <eSubpackages name="Tack control Local cloud">
      <eClassifiers xsi:type="ecore:EClass" name="TankControl-LocalCloud_Design">
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/ServiceRegistry/ServiceRegistry-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Orchestration/Orchestration-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Authorisation/Authorization-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/GateKeeper/GateKeeper-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Gateway/Gateway-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/SystemRegistry/SystemRegistry-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/DeviceRegistry/DeviceRegistry-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Onboarding/Onboarding-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/CertificateAuthority/CertificateAuthority-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Translation/Translation-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/DataManager/DataManager-Design"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="#//Tank%20control/Level/LevelSensor-Design" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="#//Tank%20control/HMI/HMI-Design" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="#//Tank%20control/Controler/Controler-Design" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="#//Tank%20control/Valve/Valve-Design" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="#//Tank%20control/Flow/FlowSensor-Design" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/EventHandler/EventHandler-Design"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TankControl-LocalCloud_DesignDescription"
          eSuperTypes="#//Tank%20control/Tack%20control%20Local%20cloud/TankControl-LocalCloud_Design">
        <eAnnotations/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/ServiceRegistry/ServiceRegistry-DesignDescription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Orchestration/Orchestration-DesignDesccription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Authorisation/Authorization-DesignDescription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/GateKeeper/GateKeeper-DesignDescription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Gateway/Gateway-DesignDescription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/SystemRegistry/SystemRegistry-DesignDescription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/DeviceRegistry/DeviceRegistry-DesignDescription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Onboarding/Onboarding-DesignDescription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/CertificateAuthority/CertificateAuthority-DesignDescription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Translation/Translation-DesignDescription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/DataManager/DataManager_DesignDescription"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="#//Tank%20control/Level/LevelSensor-DesignDescription" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="#//Tank%20control/HMI/HMI_DesignDescription" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="#//Tank%20control/Controler/Controler-DesignDescription" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="#//Tank%20control/Valve/Valve_DesignDescription" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="#//Tank%20control/Flow/FlowSensor-DesignDescription" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/EventHandler/EventHandler_DesignDescription"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TankControl-Implementation" eSuperTypes="Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Templates/Local%20Clouds/LocalCloud_DesignDescription #//Tank%20control/Tack%20control%20Local%20cloud/TankControl-LocalCloud_DesignDescription">
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/ServiceRegistry/ServiceRegistry-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Orchestration/Orchestration-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Authorisation/Authorization-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/GateKeeper/GateKeeper-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Gateway/Gateway-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/SystemRegistry/SystemRegistry-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/DeviceRegistry/DeviceRegistry-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/Onboarding/Onboarding-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" ordered="false" lowerBound="1"
            eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Core/CertificateAuthority/CertificateAuthority-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Dev-1" ordered="false"
            lowerBound="1" eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Templates/Device/Device-Implementation-BasicCore"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Dev-2" ordered="false"
            lowerBound="1" eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Templates/Device/Device-Implementation-DMZ"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="HMI-dev-1" ordered="false"
            lowerBound="1" eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Templates/Device/Device-Implementation-Application"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Flow-dev-1" ordered="false"
            lowerBound="1" eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Templates/Device/Device-Implementation-Application"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Router-1" ordered="false"
            lowerBound="1" eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Templates/Device/Device-Implementation-Router"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Level-dev-1" ordered="false"
            lowerBound="1" eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Templates/Device/Device-Implementation-Application"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Control-dev-1" ordered="false"
            lowerBound="1" eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Templates/Device/Device-Implementation-Application"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Valve-dev-1" ordered="false"
            lowerBound="1" eType="ecore:EClass Arrowhead_core_JD15d_experimental.ecore#//Arrowhead%20Templates/Device/Device-Implementation-Application"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="HMI-1" ordered="false"
            lowerBound="1" eType="#//Tank%20control/HMI/HMI-Implementation" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Flow-1" ordered="false"
            lowerBound="1" eType="#//Tank%20control/Flow/FlowSensor-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Level-1" ordered="false"
            lowerBound="1" eType="#//Tank%20control/Level/LevelSensor-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Control-1" ordered="false"
            lowerBound="1" eType="#//Tank%20control/Controler/Controler-Implementation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="Valve-1" ordered="false"
            lowerBound="1" eType="#//Tank%20control/Valve/Valve-Implementation" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" ordered="false" lowerBound="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass"/>
      <eClassifiers xsi:type="ecore:EClass"/>
      <eClassifiers xsi:type="ecore:EClass"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Derived Properties"/>
</ecore:EPackage>
