<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studio4educationprofile" nsURI="http://Papyrus/Studio4EducationProfile"
    nsPrefix="Studio4EducationProfile">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="studio4education"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="../../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="#//DeviceKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        eType="ecore:EClass ../../../org.eclipse.uml2.uml/model/UML.ecore#//Property">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Device"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceKind">
    <eLiterals name="Sensor"/>
    <eLiterals name="Actuator" value="1"/>
    <eLiterals name="Communication" value="2"/>
    <eLiterals name="X" value="3"/>
  </eClassifiers>
</ecore:EPackage>
