<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arrowheadsysmlprofile" nsURI="http://Papyrus/ArrowheadSysMLProfile"
    nsPrefix="ArrowheadSysMLProfile">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Within an IDD, a service interface with input, output and return parameters can be modeled as operations."/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="Arrowhead"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SysD" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="devicedesign" ordered="false"
        lowerBound="1" eType="#//DeviceDesign">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="device-design"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="sysd"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceDesign" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkdesign" ordered="false"
        lowerBound="1" eType="#//NetworkDesign">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="network-design"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="device-design"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkDesign" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="SysDD" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="Deployed at Device"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CertificateLevel" ordered="false"
        lowerBound="1" eType="#//CertificateKind" defaultValueLiteral="System"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devicedesigndesciption"
        ordered="false" lowerBound="1" eType="#//DeviceDesignDesciption">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="device-designdesciption"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="sysdd"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CertificateKind">
    <eLiterals name="Device"/>
    <eLiterals name="System" value="1"/>
    <eLiterals name="CoreService" value="2"/>
    <eLiterals name="ApplicationService" value="3"/>
    <eLiterals name="ManagementService" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceDesignDesciption" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CertificateLevel" ordered="false"
        lowerBound="1" eType="#//CertificateKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkDesignDescription"
        ordered="false" lowerBound="1" eType="#//NetworkDesignDescriptiion">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="network-DesignDescription"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkDesignDescriptiion" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceDesignDescription" eSuperTypes="#//ServiceDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Encoding" ordered="false"
        lowerBound="1" eType="#//EncodingKind" defaultValueLiteral="JSON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Security" ordered="false"
        lowerBound="1" eType="#//SecurityKind" defaultValueLiteral="CERTIFICATE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Protocol" ordered="false"
        lowerBound="1" eType="#//ProtocolKind" defaultValueLiteral="HTTP_1_1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Compression" ordered="false"
        lowerBound="1" eType="#//CompresionKind" defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CryptoAlgorithm" ordered="false"
        lowerBound="1" eType="#//CryptoAlgorithmKind" defaultValueLiteral="RSA"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Token" ordered="false"
        lowerBound="1" eType="#//TokenKind" defaultValueLiteral="ArrowheadToken"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CertificateLevel" ordered="false"
        lowerBound="1" eType="#//CertificateKind" defaultValueLiteral="ApplicationService"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PayloadEncryption" ordered="false"
        lowerBound="1" eType="#//PayloadEncryptionKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TimeFormat" ordered="false"
        lowerBound="1" eType="#//TimeFormatKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceDescription" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//portsandflows/InterfaceBlock"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EncodingKind">
    <eLiterals name="JSON"/>
    <eLiterals name="XML" value="1"/>
    <eLiterals name="CBOR" value="2"/>
    <eLiterals name="OTHER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SecurityKind">
    <eLiterals name="CERTIFICATE"/>
    <eLiterals name="NOT_SECURE" value="1"/>
    <eLiterals name="TOKEN" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProtocolKind">
    <eLiterals name="HTTP_0_9"/>
    <eLiterals name="HTTP_1_0" value="1"/>
    <eLiterals name="HTTP_1_1" value="2"/>
    <eLiterals name="HTTP_2_0" value="3"/>
    <eLiterals name="CoAP" value="4"/>
    <eLiterals name="CoAP_TCP" value="5"/>
    <eLiterals name="CoAPS" value="6"/>
    <eLiterals name="CoAPS_TCP" value="7"/>
    <eLiterals name="MQTT_3_1_1" value="8"/>
    <eLiterals name="MQTT_5_0" value="9"/>
    <eLiterals name="Websocket" value="10"/>
    <eLiterals name="OTHER" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompresionKind">
    <eLiterals name="EXI"/>
    <eLiterals name="OTHER" value="1"/>
    <eLiterals name="NONE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CryptoAlgorithmKind">
    <eLiterals name="RSA"/>
    <eLiterals name="EllipticCurve" value="1"/>
    <eLiterals name="DiffieHellman" value="2"/>
    <eLiterals name="Serpent" value="3"/>
    <eLiterals name="AES" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TokenKind">
    <eLiterals name="ArrowheadToken"/>
    <eLiterals name="OTHER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PayloadEncryptionKind">
    <eLiterals name="DTLS"/>
    <eLiterals name="TLS" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeFormatKind">
    <eLiterals name="RFC_3339"/>
    <eLiterals name="ISO_8601" value="1"/>
    <eLiterals name="OTHER" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubsetOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Dependency" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CertificateLevel" ordered="false"
        lowerBound="1" eType="#//CertificateKind" defaultValueLiteral="Device"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaDataEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" ordered="false" upperBound="-1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployedService">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="unnamed1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DeployedServiceName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URL" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Certificate" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" ordered="false"
        upperBound="-1" eType="#//MetaDataEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Property">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_DeployedService"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalCloudDesign" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sysd" ordered="false" upperBound="-1"
        eType="#//SysD" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="localclouddesign"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalCLoudDesignDescription" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eOperations name="getSysDD" ordered="false" lowerBound="1">
      <eParameters name="SysDD" ordered="false" lowerBound="1" eType="#//SysDD"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SysDD" ordered="false"
        upperBound="-1" eType="#//SysDD" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="LCDD"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployedDevice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Metadata" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//MetaDataEntry"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MacAddress" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NetworkInterface" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InterfaceRealization"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MacProtocol" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Property">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_DeployedDevice"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployedLocalCloud">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GatekeeperSystemName" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Property">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_DeployedLocalCloud"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSemantics">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The DataSemantics stereotype shall be used for IDD parameters: its purpose is to declare the data model (i.e., a language, an ontology, a schema or similar) used for structuring parameter values."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticModel" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ontology" ordered="false"
        upperBound="-1" eType="#//OntologyKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schema" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OntologyKind">
    <eLiterals name="SenML"/>
    <eLiterals name="ISO10303_AP203" value="1"/>
    <eLiterals name="ISO15396" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpMethodKind">
    <eLiterals name="GET"/>
    <eLiterals name="PUT" value="1"/>
    <eLiterals name="POST" value="2"/>
    <eLiterals name="DELETE" value="3"/>
    <eLiterals name="PATCH" value="4"/>
    <eLiterals name="HEAD" value="5"/>
    <eLiterals name="CONNECT" value="6"/>
    <eLiterals name="OPTIONS" value="7"/>
    <eLiterals name="TRACE" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployedEntity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The identifier of any deployed entity is a string which (ideally) uniquely identifies that given entity in an SoS.&#xD;&#xA;For making the identifiers compatible with the rest of the Arrowhead ecosystem, it is highly advisable to use the following conventions:&#xD;&#xA;System identifiers: _systemname._devicename._protocol._transport._domain&#xD;&#xA;Device identifiers: _devicename._localcloudname._interface._macâˆ’protocol._macaddress&#xD;&#xA;Local cloud identifiers: _gatekeeperâˆ’systemâˆ’name._InterCloudNegotiations. _protocol._transport._domain:port"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Property">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_DeployedEntity"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SemanticsKind">
    <eLiterals name="SenML"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceRegistryForm" eSuperTypes="#//DataSemantics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata4" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="key=data">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="metadata-4"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServiceName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="_servicename._systemname._protocol._transport._domain:port"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ProducingSystem" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="_systemname._devicename._protocol._transport._domain"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" ordered="false"
        lowerBound="1" eType="#//EncodingKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endOfValidity" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="TTL=3600s"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceURI" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="URI=http://&lt;host>:&lt;port>/service-interface"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticationInfo" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="Certificate_X509"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secure" ordered="false"
        lowerBound="1" eType="#//SecurityKind" defaultValueLiteral="CERTIFICATE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compression" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="compresion=NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata1" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="key=data">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="metadata-1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata2" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="key=data">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="metadata-2"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata3" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="key=data">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="metadata-3"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemRegistryForm" eSuperTypes="#//DataSemantics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SystemName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="_systemname._devicename._protocol._transport._domain"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HostDevice" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="_devicename._localcloudname._interface._mac-protocl._macaddress"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticationInfo" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="Certificate_X509"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endOfValidity" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="TTL= 2 month"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceURI" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="URI=http://&lt;host>:&lt;port>/service-interface"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="version=data"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deployTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="DeployTime=data"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata1" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="key=data">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="metadata-1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata2" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="key=data">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="metadata-2"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceRegistryForm" eSuperTypes="#//DataSemantics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HostDevice" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="_devicename._localcloudname._interface._mac-protocl._macaddress"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticationInfo" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="Certificate_X509"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endOfValidity" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="TTL= 2 month"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="version=data"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deployTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="DeployTime=data"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata1" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="key=data">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="metadata-1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata2" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="key=data">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="metadata-2"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CertificateCreationForm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commomName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyAlgorithm" ordered="false"
        lowerBound="1" eType="#//CryptoAlgorithmKind" defaultValueLiteral="RSA"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyFormat" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="privatKey" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicKey" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InstanceNamingStandardKind">
    <eLiterals name="ISO15296"/>
    <eLiterals name="ISO10303" value="1"/>
    <eLiterals name="BIM_v5" value="2"/>
    <eLiterals name="BIM_v4" value="3"/>
    <eLiterals name="BIM_v3" value="4"/>
    <eLiterals name="OTHER" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatusCodeKind">
    <eLiterals name="_100">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="OK"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_200" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="OK&#xA;&#xD;Normal response, no error"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_201" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Created: Normal response, no error"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_400" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Bad request&#xA;&#xD;Incorrect request"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_401" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not authorized&#xA;&#xD;Missing or faulty credentials"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_422" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unprocessable entity&#xA;Impossible to process the entity"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_500" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Internal server error&#xA;&#xD;Database failure, hardware error etc."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CoAPMetodKind">
    <eLiterals name="GET"/>
    <eLiterals name="PUT" value="1"/>
    <eLiterals name="POST" value="2"/>
    <eLiterals name="DELETE" value="3"/>
    <eLiterals name="PATCH" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchemaType">
    <eLiterals name="XML_Schema"/>
    <eLiterals name="JSON_Schema" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemofLocalCloudsDesign" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eOperations name="getLCD" ordered="false" lowerBound="1">
      <eParameters name="LCD" ordered="false" lowerBound="1" eType="#//LocalCloudDesign"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LCD" ordered="false" upperBound="-1"
        eType="#//LocalCloudDesign" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="SoLCD"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemofLocalCloudsDesignDescription"
      eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eOperations name="getLCDD" ordered="false" lowerBound="1">
      <eParameters name="LCDD" ordered="false" lowerBound="1" eType="#//LocalCLoudDesignDescription"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LCDD" ordered="false" upperBound="-1"
        eType="#//LocalCLoudDesignDescription" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="SoLCDD"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MAC"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PhysicalLayerKind">
    <eLiterals name="_802_3"/>
    <eLiterals name="_802_15_4" value="1"/>
    <eLiterals name="_802_11a" value="2"/>
    <eLiterals name="_802_11_b" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MacKind">
    <eLiterals name="CDMA"/>
    <eLiterals name="TDMA" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EngineeringProcedureKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationSysDDHTTP" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemofLocalCloudsDeployed" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eOperations name="getLocalCloudDeployed" ordered="false" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="getLocalCloud-Deployed"/>
      </eAnnotations>
      <eParameters name="localCloudsDeployed" ordered="false" upperBound="-1" eType="#//LocalCloudDeployed">
        <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
          <details key="originalName" value="localClouds-Deployed"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localCloudDeployed" ordered="false"
        upperBound="-1" eType="#//LocalCloudDeployed" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="localCloud-Deployed"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalCloudDeployed" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceDeployed" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localclouddeployed" ordered="false"
        lowerBound="1" eType="#//LocalCloudDeployed">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="localcloud-deployed"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="device-deployed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkdeployed" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//NetworkDeployed">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="network-deployed"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="device-deployed"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkDeployed" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="SDDD" eSuperTypes="#//ServiceDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="MQTT_topic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Security" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TopicName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HttpOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="#//HttpMethodKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Operation" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Operation">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_HttpOperation"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemRequirements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_System-Requirements"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkRequirements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Network-Requirements"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocaCloudRequirements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_LocaCloud-Requirements"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemofLocalCloudsRequirements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_SystemofLocalCloudsRequirements"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceRequirements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Device-Requirements"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemofLocalCloudsMaintenance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_System-of-LocalClouds-Maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemoflocalcloudsdeployed"
        ordered="false" lowerBound="1" eType="#//SystemofLocalCloudsDeployed">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="system-of-localclouds-deployed"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="system-of-localclouds-maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemofLocalCloudsEvolution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_System-of-LocalClouds-Evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemoflocalcloudsdeployed"
        ordered="false" lowerBound="1" eType="#//SystemofLocalCloudsDeployed">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="system-of-localclouds-deployed"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="system-of-localclouds-evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalCloudMaintenance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_LocalCloud-Maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemoflocalcloudsmaintenance"
        ordered="false" eType="#//SystemofLocalCloudsMaintenance">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="system-of-localclouds-maintenance"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="localcloud-maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localclouddeployed" ordered="false"
        lowerBound="1" eType="#//LocalCloudDeployed">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="localcloud-deployed"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="localcloud-maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalCloudEvolution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_LocalCloud-Evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemoflocalcloudsevolution"
        ordered="false" eType="#//SystemofLocalCloudsEvolution">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="system-of-localclouds-evolution"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="localcloud-evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localclouddeployed" ordered="false"
        lowerBound="1" eType="#//LocalCloudDeployed">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="localcloud-deployed"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="localcloud-evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SysMaintenance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Sys-Maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sysimplementation" ordered="false"
        lowerBound="1" eType="#//SysImplementation">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="sys-implementation"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="sys-maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localcloudmaintenance"
        ordered="false" lowerBound="1" eType="#//LocalCloudMaintenance">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="localcloud-maintenance"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="sys-maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devicemaintenance" ordered="false"
        lowerBound="1" eType="#//DeviceMaintenance">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="device-maintenance"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="sys-maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SysImplementation" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localcloudimplementation"
        ordered="false" lowerBound="1" eType="#//LocalCLoudImplementation">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="localcloud-implementation"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="sys-implementation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceimplementation" ordered="false"
        lowerBound="1" eType="#//DeviceImplementation">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="device-implementation"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="sys-implementation"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalCLoudImplementation" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemoflocalcloudsimplementation"
        ordered="false" upperBound="-1" eType="#//SystemofLocalCloudsImplementation">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="system-of-localclouds-implementation"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="localcloud-implementation"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemofLocalCloudsImplementation" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceImplementation" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkimplementation"
        ordered="false" lowerBound="1" upperBound="-1" eType="#//NetworkImplementation">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="network-implementation"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="device-implementation"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkImplementation" eSuperTypes="../../org.eclipse.papyrus.sysml16/resources/profile/SysML.profile.ecore#//blocks/Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceMaintenance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Device-Maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devicedeployed" ordered="false"
        lowerBound="1" eType="#//DeviceDeployed">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="device-deployed"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="device-maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkmaintenance" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//NetworkMaintenance">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="network-maintenance"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="device-maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkMaintenance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Network-Maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkdeployed" ordered="false"
        lowerBound="1" eType="#//NetworkDeployed">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="network-deployed"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="network-maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SysEvolution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Sys-Evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localcloudevolution" ordered="false"
        lowerBound="1" eType="#//LocalCloudEvolution">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="localcloud-evolution"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="sys-evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sysimplementation" ordered="false"
        lowerBound="1" eType="#//SysImplementation">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="sys-implementation"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="sys-evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceevolution" ordered="false"
        lowerBound="1" eType="#//DeviceEvolution">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="device-evolution"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="sys-evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceEvolution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Device-Evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkevolution" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//NetworkEvolution">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="network-evolution"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="device-evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devicedeployed" ordered="false"
        lowerBound="1" eType="#//DeviceDeployed">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="device-deployed"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="device-evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkEvolution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Network-Evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkdeployed" ordered="false"
        lowerBound="1" eType="#//NetworkDeployed">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="network-deployed"/>
      </eAnnotations>
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="network-evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deployment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Deployment"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Requirements"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalDesign">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_FunctionalDesign"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcurementAndEngineering">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Procurement&amp;Engineering"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Maintenance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Maintenance"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Evolution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_Evolution"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SysDeployed">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChoreographyDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Collaboration" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Collaboration">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="extension_ChoreographyDefinition"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OSKind">
    <eLiterals name="Linux"/>
    <eLiterals name="MacOS" value="1"/>
    <eLiterals name="Windows" value="2"/>
    <eLiterals name="ROS" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LinuxKind">
    <eLiterals name="Ubuntu_20_10"/>
    <eLiterals name="Ubuntu_20_04_LTS" value="1"/>
    <eLiterals name="Ubuntu_Raspberry_Pi_2" value="2"/>
    <eLiterals name="Ubuntu_Raspberry_Pi_3" value="3"/>
    <eLiterals name="Ubuntu_Raspberry_Pi_4" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeploymentLocationKind">
    <eLiterals name="Coordinates"/>
    <eLiterals name="LocationID" value="1"/>
    <eLiterals name="PowerID" value="2"/>
    <eLiterals name="NetworkID" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeploymentTimeKind">
    <eLiterals name="DeploymentTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceKind">
    <eLiterals name="STM32"/>
    <eLiterals name="RaspbeeryPI" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProcessortKind">
    <eLiterals name="ARM_M1"/>
    <eLiterals name="ARM_M2" value="1"/>
  </eClassifiers>
</ecore:EPackage>
