<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Arrowhead">
  <eClassifiers xsi:type="ecore:EEnum" name="SecurityKind">
    <eLiterals name="CERTIFICATE"/>
    <eLiterals name="NOT_SECURE"/>
    <eLiterals name="TOKEN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpMethodKind">
    <eLiterals name="GET"/>
    <eLiterals name="PUT"/>
    <eLiterals name="POST"/>
    <eLiterals name="DELETE"/>
    <eLiterals name="PATCH"/>
    <eLiterals name="HEAD"/>
    <eLiterals name="CONNECT"/>
    <eLiterals name="OPTIONS"/>
    <eLiterals name="TRACE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EncodingKind">
    <eLiterals name="JSON"/>
    <eLiterals name="XML"/>
    <eLiterals name="CBOR"/>
    <eLiterals name="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompresionKind">
    <eLiterals name="EXI"/>
    <eLiterals name="OTHER"/>
    <eLiterals name="NONE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SemanticsKind">
    <eLiterals name="SenML"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CertificateKind">
    <eLiterals name="Device"/>
    <eLiterals name="System"/>
    <eLiterals name="CoreService"/>
    <eLiterals name="ApplicationService"/>
    <eLiterals name="ManagementService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProtocolKind">
    <eLiterals name="HTTP 0.9"/>
    <eLiterals name="HTTP 1.0"/>
    <eLiterals name="HTTP 1.1"/>
    <eLiterals name="HTTP 2.0"/>
    <eLiterals name="CoAP"/>
    <eLiterals name="CoAP TCP"/>
    <eLiterals name="CoAPS"/>
    <eLiterals name="CoAPS TCP"/>
    <eLiterals name="MQTT 3.1.1"/>
    <eLiterals name="MQTT 5.0"/>
    <eLiterals name="Websocket"/>
    <eLiterals name="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TokenKind">
    <eLiterals name="ArrowheadToken"/>
    <eLiterals name="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CryptoAlgorithmKind">
    <eLiterals name="RSA"/>
    <eLiterals name="EllipticCurve"/>
    <eLiterals name="DiffieHellman"/>
    <eLiterals name="Serpent"/>
    <eLiterals name="AES"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InstanceNamingStandardKind">
    <eLiterals name="ISO15926"/>
    <eLiterals name="ISO10303"/>
    <eLiterals name="BIM v5"/>
    <eLiterals name="BIM v4"/>
    <eLiterals name="BIM v3"/>
    <eLiterals name="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PayloadEncryptionKind">
    <eLiterals name="DTLS"/>
    <eLiterals name="TLS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatusCodeKind">
    <eLiterals name="100">
      <eAnnotations source="OK" references="#//StatusCodeKind/100">
        <eAnnotations/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="200">
      <eAnnotations source="OK&#xA;&#xD;Normal response, no error" references="#//StatusCodeKind/200"/>
    </eLiterals>
    <eLiterals name="201">
      <eAnnotations source="Created: Normal response, no error" references="#//StatusCodeKind/201"/>
    </eLiterals>
    <eLiterals name="400">
      <eAnnotations source="Bad request&#xA;&#xD;Incorrect request" references="#//StatusCodeKind/400"/>
    </eLiterals>
    <eLiterals name="401">
      <eAnnotations source="Not authorized&#xA;&#xD;Missing or faulty credentials"
          references="#//StatusCodeKind/401"/>
    </eLiterals>
    <eLiterals name="500">
      <eAnnotations source="Internal server error&#xA;&#xD;Database failure, hardware error etc."
          references="#//StatusCodeKind/500"/>
    </eLiterals>
    <eLiterals name="422">
      <eAnnotations source="Unprocessable entity&#xA;Impossible to process the entity"
          references="#//StatusCodeKind/422"/>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CoAPMetodKind">
    <eLiterals name="GET"/>
    <eLiterals name="PUT"/>
    <eLiterals name="POST"/>
    <eLiterals name="DELETE"/>
    <eLiterals name="PATCH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeFormatKind">
    <eLiterals name="RFC 3339"/>
    <eLiterals name="ISO 8601"/>
    <eLiterals name="Unix time"/>
    <eLiterals name="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OntologyKind">
    <eLiterals name="SenML"/>
    <eLiterals name="ISO10303 AP203"/>
    <eLiterals name="ISO15396"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchemaType">
    <eLiterals name="XML Schema"/>
    <eLiterals name="JSON Schema"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PhysicalLayerKind">
    <eLiterals name="802.3"/>
    <eLiterals name="802.15.4"/>
    <eLiterals name="802.11a"/>
    <eLiterals name="802.11.b"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MacKind">
    <eLiterals name="CDMA"/>
    <eLiterals name="TDMA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OSKind">
    <eLiterals name="Linux"/>
    <eLiterals name="MacOS"/>
    <eLiterals name="Windows"/>
    <eLiterals name="ROS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LinuxKind">
    <eLiterals name="Ubuntu 20.10"/>
    <eLiterals name="Ubuntu 20.04 LTS"/>
    <eLiterals name="Ubuntu Raspberry Pi 2"/>
    <eLiterals name="Ubuntu Raspberry Pi 3"/>
    <eLiterals name="Ubuntu Raspberry Pi 4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeploymentLocationKind">
    <eLiterals name="Coordinates"/>
    <eLiterals name="Location ID"/>
    <eLiterals name="Power ID"/>
    <eLiterals name="Network ID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeploymentTimeKind">
    <eLiterals name="Deployment time"/>
  </eClassifiers>
</ecore:EPackage>
